### ISSUE TITLE
Documentation error in Kilolib

### ISSUE THREAD

**Issue by mickael9** [acornejo/kilogui#4]
https://www.kilobotics.com/docs/kilolib_8h.html#a40acdda801b020e80642b108e541e717

``` c
void rx_message(message_t *msg, distance_message_t *dist) {
    recvd_message = 1;
}
```

`distance_message_t` should be changed to `distance_measurement_t`

**Comment by acornejo** [comment]
Thank you! good catch. All bug reports are VERY appreciated. Already corrected this one (will update the webpage later tonight). Feel free to post anyother bug reports in the kilolib repository

https://github.com/acornejo/kilolib
