### ISSUE TITLE
Can't get new kilobot gui to work on windows

### ISSUE THREAD

**Issue by dsbrown1331** [acornejo/kilogui#6]
I've been to the Kilobotics.com website and followed the instructions to update the firmware of the overhead controller. However, when I run the kilogui.exe it says "device not found" and wont let me connect to the controller.

**Comment by acornejo** [comment]
You need to install the libusb-win32 driver to use the ftdi chipnon the
controller. Instructions are on the website. If you are using windows 8 try
zadig instead.
